# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest


    ports:
      - '5433:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_DB=mydatabase'
      - 'POSTGRESQL_USER=myuser'
      - 'POSTGRESQL_PASSWORD=mypassword'

volumes:
  postgresql_data:
    driver: local